name: Learning
on:
  workflow_dispatch:
jobs:
  test01:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
     # Docker-Compose setup
      - name: Setup docker compose
        run: docker-compose up -d 
     #Setup Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install software
        run: sudo apt-get install -y chromium-browser
      - name: Install the necessary packages
        run: pip install webdriver-manager selenium pytest
      - name: Run the PytTest script
        run: pytest -rA
